### ISSUE TITLE
Decide how to proceed with connector

### ISSUE THREAD

**Issue by cmgrote** [odpi/egeria-connector-apache-atlas#5]
It seems that implementing the reference copy handling won't be possible per #4.

Options for proceeding:

1. Make the connector read-only.
1. Allow creates and updates (via `addEntity`, etc -- just not the reference copy equivalents). We will also need:
    - a fix for #3 as we will need change notifications for any write activities on a home repository
    - to decide how to handle cases where a composition of objects is needed (eg. cannot create an `AtlasGlossaryCategory` without an `AtlasGlossary` and defining the `anchor` on the `AtlasGlossaryCategory`)

Also need to decide scope of these:

- For all Open Metadata types (ie. add the new types)?
- For only the out-of-the-box Atlas types?

And in each of those cases:

- How to handle a mis-match in the types eg. extra properties or relationships in Open Metadata type that do not exist in Atlas:
    - always use null values (only works for a read-only connector)?
    - extend pre-existing Atlas types with extra properties (invasive, but allows writes)?

**Comment by mandy-chessell** [comment]
I think going for a read only version to start with is a good option.  If there are demands for storing metadata in Atlas then we can work with the Atlas team to get the fixes we need.

For the read-only (publishing) connector, just omit the properties that are not included in the Atlas model rather than setting them to null values.

If/when we extend the connector to write metadata into Atlas, I would suggest focusing on the built in types because there is likely to be Atals support for using the metadata once loaded.

**Comment by cmgrote** [comment]
Makes sense -- I was thinking of also starting with the Classifications from open metadata (just those that apply to the Atlas out-of-the-box types), since there are no out-of-the-box Classifications.
